bibGest/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using bibGest.Data;
using bibGest.Models;

namespace bibGest.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly BibliothequeContext _context;

        public CategoriesController(BibliothequeContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategorieId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NomCategorie,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategorieId,NomCategorie,Description")] Category category)
        {
            if (id != category.CategorieId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategorieId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategorieId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CategorieId == id);
        }
    }
}

bibGest/Controllers/LivresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using bibGest.Data;
using bibGest.Models;

namespace bibGest.Controllers
{
    public class LivresController : Controller
    {
        private readonly BibliothequeContext _context;

        public LivresController(BibliothequeContext context)
        {
            _context = context;
        }

        // GET: Livres
        public async Task<IActionResult> Index()
        {
            var bibliothequeContext = _context.Livres.Include(l => l.Categorie);
            return View(await bibliothequeContext.ToListAsync());
        }

        // GET: Livres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livre = await _context.Livres
                .Include(l => l.Categorie)
                .FirstOrDefaultAsync(m => m.LivreId == id);
            if (livre == null)
            {
                return NotFound();
            }

            return View(livre);
        }

        // GET: Livres/Create
        public IActionResult Create()
        {
            ViewData["CategorieId"] = new SelectList(_context.Categories, "CategorieId", "NomCategorie");
            var livre = new Livre
            {
                QuantiteTotale = 1,
                QuantiteDisponible = 1
            };
            return View(livre);
        }

        // POST: Livres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Titre,Auteur,Isbn,AnneePublication,Description,ImageUrl,QuantiteTotale,QuantiteDisponible,CategorieId")] Livre livre)
        {
            // Remove validation errors for navigation properties
            ModelState.Remove("Categorie");
            ModelState.Remove("Emprunts");
            ModelState.Remove("Reservations");
            
            if (ModelState.IsValid)
            {
                _context.Add(livre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategorieId"] = new SelectList(_context.Categories, "CategorieId", "NomCategorie", livre.CategorieId);
            return View(livre);
        }

        // GET: Livres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livre = await _context.Livres.FindAsync(id);
            if (livre == null)
            {
                return NotFound();
            }
            ViewData["CategorieId"] = new SelectList(_context.Categories, "CategorieId", "NomCategorie", livre.CategorieId);
            return View(livre);
        }

        // POST: Livres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LivreId,Titre,Auteur,Isbn,AnneePublication,Description,ImageUrl,QuantiteTotale,QuantiteDisponible,CategorieId")] Livre livre)
        {
            if (id != livre.LivreId)
            {
                return NotFound();
            }

            // Remove validation errors for navigation properties
            ModelState.Remove("Categorie");
            ModelState.Remove("Emprunts");
            ModelState.Remove("Reservations");

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(livre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivreExists(livre.LivreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategorieId"] = new SelectList(_context.Categories, "CategorieId", "NomCategorie", livre.CategorieId);
            return View(livre);
        }

        // GET: Livres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livre = await _context.Livres
                .Include(l => l.Categorie)
                .FirstOrDefaultAsync(m => m.LivreId == id);
            if (livre == null)
            {
                return NotFound();
            }

            return View(livre);
        }

        // POST: Livres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var livre = await _context.Livres.FindAsync(id);
            if (livre != null)
            {
                _context.Livres.Remove(livre);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LivreExists(int id)
        {
            return _context.Livres.Any(e => e.LivreId == id);
        }
    }
}

bibGest/Controllers/PenalitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using bibGest.Data;
using bibGest.Models;

namespace bibGest.Controllers
{
    public class PenalitesController : Controller
    {
        private readonly BibliothequeContext _context;

        public PenalitesController(BibliothequeContext context)
        {
            _context = context;
        }

        // GET: Penalites
        public async Task<IActionResult> Index()
        {
            var bibliothequeContext = _context.Penalites.Include(p => p.Emprunt);
            return View(await bibliothequeContext.ToListAsync());
        }

        // GET: Penalites/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var penalite = await _context.Penalites
                .Include(p => p.Emprunt)
                .FirstOrDefaultAsync(m => m.PenaliteId == id);
            if (penalite == null)
            {
                return NotFound();
            }

            return View(penalite);
        }

        // GET: Penalites/Create
        public IActionResult Create()
        {
            ViewData["EmpruntId"] = new SelectList(
                _context.Emprunts
                    .Include(e => e.Livre)
                    .Include(e => e.Utilisateur)
                    .Select(e => new { 
                        e.EmpruntId, 
                        Description = e.Livre.Titre + " - " + e.Utilisateur.Nom + " " + e.Utilisateur.Prenom 
                    })
                    .ToList(), 
                "EmpruntId", 
                "Description");
            var penalite = new Penalite
            {
                DateCreation = DateTime.Now,
                EstPayee = false
            };
            return View(penalite);
        }

        // POST: Penalites/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmpruntId,Montant,EstPayee")] Penalite penalite)
        {
            // Remove validation errors for navigation properties
            ModelState.Remove("Emprunt");
            
            if (ModelState.IsValid)
            {
                penalite.DateCreation = DateTime.Now;
                _context.Add(penalite);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            ViewData["EmpruntId"] = new SelectList(
                _context.Emprunts
                    .Include(e => e.Livre)
                    .Include(e => e.Utilisateur)
                    .Select(e => new { 
                        e.EmpruntId, 
                        Description = e.Livre.Titre + " - " + e.Utilisateur.Nom + " " + e.Utilisateur.Prenom 
                    })
                    .ToList(), 
                "EmpruntId", 
                "Description", 
                penalite.EmpruntId);
            return View(penalite);
        }

        // GET: Penalites/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var penalite = await _context.Penalites.FindAsync(id);
            if (penalite == null)
            {
                return NotFound();
            }
            ViewData["EmpruntId"] = new SelectList(
                _context.Emprunts
                    .Include(e => e.Livre)
                    .Include(e => e.Utilisateur)
                    .Select(e => new { 
                        e.EmpruntId, 
                        Description = e.Livre.Titre + " - " + e.Utilisateur.Nom + " " + e.Utilisateur.Prenom 
                    })
                    .ToList(), 
                "EmpruntId", 
                "Description", 
                penalite.EmpruntId);
            return View(penalite);
        }

        // POST: Penalites/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PenaliteId,EmpruntId,Montant,DateCreation,EstPayee")] Penalite penalite)
        {
            if (id != penalite.PenaliteId)
            {
                return NotFound();
            }

            // Remove validation errors for navigation properties
            ModelState.Remove("Emprunt");

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(penalite);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PenaliteExists(penalite.PenaliteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpruntId"] = new SelectList(
                _context.Emprunts
                    .Include(e => e.Livre)
                    .Include(e => e.Utilisateur)
                    .Select(e => new { 
                        e.EmpruntId, 
                        Description = e.Livre.Titre + " - " + e.Utilisateur.Nom + " " + e.Utilisateur.Prenom 
                    })
                    .ToList(), 
                "EmpruntId", 
                "Description", 
                penalite.EmpruntId);
            return View(penalite);
        }

        // GET: Penalites/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var penalite = await _context.Penalites
                .Include(p => p.Emprunt)
                .FirstOrDefaultAsync(m => m.PenaliteId == id);
            if (penalite == null)
            {
                return NotFound();
            }

            return View(penalite);
        }

        // POST: Penalites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var penalite = await _context.Penalites.FindAsync(id);
            if (penalite != null)
            {
                _context.Penalites.Remove(penalite);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PenaliteExists(int id)
        {
            return _context.Penalites.Any(e => e.PenaliteId == id);
        }
    }
}

bibGest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BibGest</title>
    
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Bootstrap & Icons -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css" />
    
    <!-- Custom Styles -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/bibGest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid px-4">
                <a class="navbar-brand d-flex align-items-center" asp-controller="Home" asp-action="Index">
                    <div class="bg-white text-primary rounded-circle d-flex align-items-center justify-content-center me-2" 
                         style="width: 36px; height: 36px;">
                        <i class="bi bi-book-half"></i>
                    </div>
                    <span>BibGest</span>
                </a>
                <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarMain">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">
                                <i class="bi bi-house me-1"></i>Accueil
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Catalog" asp-action="Index">
                                <i class="bi bi-grid-3x3-gap me-1"></i>Catalogue
                            </a>
                        </li>
                        @if (User.Identity?.IsAuthenticated == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
                                    <i class="bi bi-speedometer2 me-1"></i>Mon Espace
                                </a>
                            </li>
                            
                            @if (User.IsInRole("Bibliothecaire") || User.IsInRole("Administrateur"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                                        <i class="bi bi-gear me-1"></i>Gestion
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-start shadow-lg">
                                        <li class="px-2 py-1">
                                            <span class="dropdown-header text-uppercase small fw-bold text-muted">Bibliothèque</span>
                                        </li>
                                        <li><a class="dropdown-item" asp-controller="Livres" asp-action="Index">
                                            <i class="bi bi-book me-2 text-primary"></i>Livres
                                        </a></li>
                                        <li><a class="dropdown-item" asp-controller="Emprunts" asp-action="Index">
                                            <i class="bi bi-arrow-left-right me-2 text-info"></i>Emprunts
                                        </a></li>
                                        <li><a class="dropdown-item" asp-controller="Reservations" asp-action="Index">
                                            <i class="bi bi-bookmark me-2 text-warning"></i>Réservations
                                        </a></li>
                                        @if (User.IsInRole("Administrateur"))
                                        {
                                            <li><hr class="dropdown-divider my-2"></li>
                                            <li class="px-2 py-1">
                                                <span class="dropdown-header text-uppercase small fw-bold text-muted">Administration</span>
                                            </li>
                                            <li><a class="dropdown-item" asp-controller="Utilisateurs" asp-action="Index">
                                                <i class="bi bi-people me-2 text-success"></i>Utilisateurs
                                            </a></li>
                                            <li><a class="dropdown-item" asp-controller="Categories" asp-action="Index">
                                                <i class="bi bi-tags me-2 text-secondary"></i>Catégories
                                            </a></li>
                                            <li><a class="dropdown-item" asp-controller="Penalites" asp-action="Index">
                                                <i class="bi bi-exclamation-circle me-2 text-danger"></i>Pénalités
                                            </a></li>
                                        }
                                    </ul>
                                </li>
                            }
                        }
                    </ul>
                    
                    <!-- Search Form -->
                    <form class="d-none d-lg-flex me-3" asp-controller="Catalog" asp-action="Index" method="get">
                        <div class="input-group">
                            <span class="input-group-text bg-white border-end-0">
                                <i class="bi bi-search text-muted"></i>
                            </span>
                            <input type="text" name="search" class="form-control bg-white border-start-0 ps-0" 
                                   placeholder="Rechercher un livre..." style="min-width: 200px;" />
                        </div>
                    </form>
                    
                    <!-- User Menu -->
                    <ul class="navbar-nav">
                        @if (User.Identity?.IsAuthenticated == true)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" role="button" data-bs-toggle="dropdown">
                                    <div class="avatar bg-white text-primary me-2" style="width: 32px; height: 32px; font-size: 0.75rem;">
                                        @User.Identity.Name?.Substring(0, Math.Min(2, User.Identity.Name?.Length ?? 0)).ToUpper()
                                    </div>
                                    <span class="d-none d-lg-inline">@User.Identity.Name</span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end shadow-lg">
                                    <li class="px-3 py-2">
                                        <div class="fw-bold">@User.Identity.Name</div>
                                        <small class="text-muted">@User.FindFirst(System.Security.Claims.ClaimTypes.Role)?.Value</small>
                                    </li>
                                    <li><hr class="dropdown-divider my-1"></li>
                                    <li><a class="dropdown-item" asp-controller="Dashboard" asp-action="Index">
                                        <i class="bi bi-speedometer2 me-2 text-primary"></i>Tableau de bord
                                    </a></li>
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Profile">
                                        <i class="bi bi-person me-2 text-secondary"></i>Mon profil
                                    </a></li>
                                    <li><hr class="dropdown-divider my-1"></li>
                                    <li>
                                        <form asp-controller="Account" asp-action="Logout" method="post" class="px-2">
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="dropdown-item text-danger rounded">
                                                <i class="bi bi-box-arrow-right me-2"></i>Déconnexion
                                            </button>
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Login">
                                    <i class="bi bi-box-arrow-in-right me-1"></i>Connexion
                                </a>
                            </li>
                            <li class="nav-item ms-2">
                                <a class="btn btn-light btn-sm px-3" asp-controller="Account" asp-action="Register">
                                    <i class="bi bi-person-plus me-1"></i>S'inscrire
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="flex-grow-1 py-4">
        <div class="container-fluid px-4">
            <!-- Toast Notifications -->
            @if (TempData["Success"] != null)
            {
                <div class="alert alert-success alert-dismissible fade show mb-4" role="alert">
                    <i class="bi bi-check-circle me-2"></i>@TempData["Success"]
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            }
            @if (TempData["Error"] != null)
            {
                <div class="alert alert-danger alert-dismissible fade show mb-4" role="alert">
                    <i class="bi bi-exclamation-circle me-2"></i>@TempData["Error"]
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            }
            
            @RenderBody()
        </div>
    </main>

    <footer class="py-4">
        <div class="container-fluid px-4">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <div class="d-flex align-items-center text-white">
                        <div class="bg-white bg-opacity-10 rounded-circle d-flex align-items-center justify-content-center me-3" 
                             style="width: 40px; height: 40px;">
                            <i class="bi bi-book-half text-white"></i>
                        </div>
                        <div>
                            <h6 class="mb-0 fw-bold">BibGest</h6>
                            <small class="text-white-50">Système de gestion de bibliothèque</small>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 text-md-end mt-3 mt-md-0">
                    <small class="text-white-50">&copy; @DateTime.Now.Year BibGest. Tous droits réservés.</small>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>